### ISSUE TITLE
Submit Project Proposal

### ISSUE THREAD

**Issue by rkpalmerjr** [bryangarner/GEOG575_Finalproject#14]
Completed sections:
- [x] Persona/Scenario - Issue #9 
- [x] Requirements Document - Issue #10  
- [x] Lo-fi Wireframes  - Issue #11 

- [x] Proposal Submitted
